/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as GameGameIdEndRouteImport } from './routes/game.$gameId.end'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdEndRoute = GameGameIdEndRouteImport.update({
  id: '/end',
  path: '/end',
  getParentRoute: () => GameGameIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$gameId': typeof GameGameIdRouteWithChildren
  '/game/$gameId/end': typeof GameGameIdEndRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$gameId': typeof GameGameIdRouteWithChildren
  '/game/$gameId/end': typeof GameGameIdEndRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/$gameId': typeof GameGameIdRouteWithChildren
  '/game/$gameId/end': typeof GameGameIdEndRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game/$gameId' | '/game/$gameId/end'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game/$gameId' | '/game/$gameId/end'
  id: '__root__' | '/' | '/game/$gameId' | '/game/$gameId/end'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameGameIdRoute: typeof GameGameIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId/end': {
      id: '/game/$gameId/end'
      path: '/end'
      fullPath: '/game/$gameId/end'
      preLoaderRoute: typeof GameGameIdEndRouteImport
      parentRoute: typeof GameGameIdRoute
    }
  }
}

interface GameGameIdRouteChildren {
  GameGameIdEndRoute: typeof GameGameIdEndRoute
}

const GameGameIdRouteChildren: GameGameIdRouteChildren = {
  GameGameIdEndRoute: GameGameIdEndRoute,
}

const GameGameIdRouteWithChildren = GameGameIdRoute._addFileChildren(
  GameGameIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameGameIdRoute: GameGameIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

export {}
